// src/lib/components/FormattedDate.svelte
<script lang="ts">
	import dayjs from 'dayjs';
	import type { HTMLTimeAttributes } from 'svelte/elements';

	interface Props extends HTMLTimeAttributes {
		date: Date;
	}

	const { date, class: className, ...rest }: Props = $props();
</script>

<time dateTime={date.toISOString()} class={className} {...rest}>
	{dayjs(date).format('MMM DD, YYYY')}
</time>

// src/components/FormattedDate.tsx
import dayjs from "dayjs";

interface Props {
  date: Date;
  className?: HTMLTimeElement["className"];
}

export function FormattedDate({ date, className }: Props) {
  return (
    <time dateTime={date.toISOString()} className={className}>
      {dayjs(date).format("MMM DD, YYYY")}
    </time>
  );
}
