// src/routes/blog/+page.svelte
<script>
	import FormattedDate from '$lib/components/FormattedDate.svelte';
	import Link from '$lib/components/Link.svelte';

	const { data } = $props();
	// svelte-ignore state_referenced_locally
	const { posts } = data;
</script>

<h1 class="mt-0">Blog</h1>
<section class="space-y-4">
	<ul>
		{#each posts as post}
			<li>
				<FormattedDate
					date={new Date(post.metadata.date)}
					class="font-mono text-base text-nowrap"
				/>:
				<Link href={`/blog/${post.slug}`} class="no-underline">
					{post.metadata.title}
				</Link>
			</li>
		{/each}
	</ul>
</section>

// src/app/blog/page.tsx
import { FormattedDate } from "@/components/FormattedDate";
import { getAllPosts } from "@/lib/api";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
};

export default function Blog() {
  const posts = getAllPosts();
  return (
    <section className="space-y-4">
      {posts.map((post) => (
        <div
          className="flex flex-col-reverse sm:flex-row sm:items-start gap-0.5 sm:gap-4"
          key={post.slug}
        >
          <FormattedDate
            date={new Date(post.date)}
            className="text-nowrap font-mono text-xs sm:text-base"
          />
          <a href={`/blog/${post.slug}/`} className="no-underline sm:-mt-[2px]">
            <h4 className="m-0">{post.title}</h4>
          </a>
        </div>
      ))}
    </section>
  );
}
