// src/components/InlineCode.tsx
import { clsx } from "@/util";
import { PropsWithChildren } from "react";

interface Props extends PropsWithChildren {
  className?: string;
}

export function InlineCode(props: Props) {
  return (
    <code
      className={clsx(
        "bg-gray-100 border border-black/10 rounded font-mono text-sm px-1 py-0.5 w-fit",
        props.className
      )}
    >
      {props.children}
    </code>
  );
}

// src/lib/components/InlineCode.svelte
<script lang="ts">
	import type { PropsWithChildren } from '$lib/utils';
	import type { HTMLAttributes } from 'svelte/elements';

	interface Props extends HTMLAttributes<HTMLElement> {}

	const { children, class: className, ...rest }: PropsWithChildren<Props> = $props();
</script>

<code
	class={[
		'w-fit rounded border border-black/10 bg-gray-100 px-1 py-0.5 font-mono text-sm',
		className
	]}
	{...rest}
>
	{@render children?.()}
</code>
