// src/components/Link.tsx
import { ensureTrailingSlash } from '@/utils';

export function Link({ href: h, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) {
	let href = h;
	if (href) {
		href = ensureTrailingSlash(href.toString());
	}

	const isExternal =
		href?.toString().startsWith('http://') || href?.toString().startsWith('https://');
	const externalAttrs = isExternal ? { target: '_blank', rel: 'noopener noreferrer' } : {};

	return (
		<a {...props} href={href} {...externalAttrs}>
			{props.children}
		</a>
	);
}

// src/lib/components/Link.svelte
<script lang="ts">
	import type { PropsWithChildren } from '$lib/utils';
	import type { HTMLAnchorAttributes } from 'svelte/elements';

	interface Props extends HTMLAnchorAttributes {}

	let { href, children, ...rest }: PropsWithChildren<Props> = $props();
	// svelte-ignore state_referenced_locally
	href = href || '';

	// svelte-ignore state_referenced_locally
	const isExternal = href.startsWith('http://') || href.startsWith('https://');
	const externalAttrs = isExternal ? { target: '_blank', rel: 'noopener noreferrer' } : {};
</script>

<a {href} {...externalAttrs} {...rest}>
	{@render children?.()}
</a>
